belajar_dbt:
  outputs:
    dev:
      dbname: penjualan
      host: localhost
      pass: '1234'
      port: 5432
      schema: global
      threads: 1
      type: postgres
      user: postgres
    prod:
      dbname: penjualan
      host: localhost
      pass: postgres
      port: 5432
      schema: global
      threads: 1
      type: postgres
      user: postgres
  target: dev